### ISSUE TITLE
No B

### ISSUE THREAD

**Issue by MackenzieHamilton** [mishra-lab/age-patch-mobility-mixing#8]
Why isn't B f referenced in this function? https://github.com/mishra-lab/age-patch-mobility-mixing/blob/d4b77310c554d1a95647961e624731b8e2f3453b/code/mix/mixing.r#L210

**Comment by jessexknight** [comment]
I think `B` is referenced subtly [here](https://github.com/mishra-lab/age-patch-mobility-mixing/blob/main/code/mix/data.r#L47) within the function, where it is used to select one of several possible columns, each being a different approximation of mobility "B" -- i.e. the `B` function argument might be `'B'` (empiric data) or `'Ba'` (approximation), those are the only implemented ones currently. The source data is [this csv](https://github.com/mishra-lab/age-patch-mobility-mixing/blob/main/data/mobility_decile.csv).

**Comment by jessexknight** [comment]
Ooh also just to clarify, the raw csv file gets loaded into the variable `mob`, and then `B` function argument selects the column

**Comment by MackenzieHamilton** [comment]
ahh so the default B = 'B' and in other instances we are passing a different B such as 'Bc' or 'Ba'
